#include <stdio.h>

/*
Instructions:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int numero;

int par(int numero){
    int res = numero % 2;
    if(res == 0){
	return numero;
    }
    return 0;
}

int fibonacci(int numero){
   if(numero == 0) {
      return 0;
   }else if(numero == 1) {
      return 1;
   }else
	return fibonacci(numero - 1) + fibonacci(numero - 2);
}

int  main() {
   int contador = 2;
   int suma;
   for (contador; fibonacci(contador) <= 4000000; contador++) { 
      printf("%d - %d\n",contador-1, fibonacci(contador));
      suma += par(fibonacci(contador));
   }
      printf("Total: %d\n", suma );
   return 0;
}
